name: docker-release

on:
  release:
    types:
      - published

jobs:
  deploy:
    if: "!github.event.release.prerelease"
    name: Build and publish to docker hub
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      SERVICE_NAME: ilert-kube-agent
      REGISTRY: ilert

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push image
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${REGISTRY}/${SERVICE_NAME}:${IMAGE_TAG} -t ${REGISTRY}/${SERVICE_NAME}:latest .
          docker push ${REGISTRY}/${SERVICE_NAME}:${IMAGE_TAG}
          docker push ${REGISTRY}/${SERVICE_NAME}:latest
          echo "::set-output name=image::${REGISTRY}/${SERVICE_NAME}:${IMAGE_TAG}"
